# Generated by Django 4.0 on 2022-01-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NocRegions',
            fields=[
                ('noc', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('height', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('age', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=20)),
                ('noc', models.CharField(max_length=5)),
                ('games', models.CharField(max_length=15)),
                ('sport', models.CharField(max_length=25)),
                ('event', models.CharField(max_length=90)),
                ('medal', models.CharField(max_length=10)),
            ],
        ),
    ]
