# Generated by Django 4.0 on 2022-01-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadinfo',
            name='games',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.olympiadinfo', to_field='games'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.nocregions'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player'),
        ),
    ]
