# Generated by Django 4.0 on 2022-01-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_olympiadinfo_games_alter_statistics_games_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Athlete',
        ),
    ]
