# Generated by Django 4.0 on 2022-01-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_player_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='noc',
            new_name='country_code',
        ),
    ]
