# Generated by Django 4.0 on 2022-01-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_noc_nocregions_country_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NocRegions',
            new_name='Country',
        ),
    ]
