# Generated by Django 4.0 on 2022-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_rename_nocregions_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
