# Generated by Django 4.0 on 2022-01-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_statistics_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='age',
            field=models.IntegerField(),
        ),
    ]
