# Generated by Django 4.0 on 2022-01-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_athlete_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadinfo',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=10),
        ),
    ]
